import { useEffect, useId, useRef } from "react";
import { Icon } from "../ui/icon";
import { IconButton } from "../ui/icon-button";

type Props = {
  value: string;
  onValueChange: (value: string) => void;
  /** Without a handler the composer stays presentation-only. */
  onSubmit?: (value: string) => void;
  disabled?: boolean;
  busy?: boolean;
  /** Submission failure, shown next to the composer. */
  error?: string | null;
};

/** Controlled composer. It stores text through the server; it never calls a model. */
export function MessageComposer({
  value,
  onValueChange,
  onSubmit,
  disabled = false,
  busy = false,
  error = null,
}: Props) {
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const inputId = useId();
  const hintId = useId();
  useEffect(() => {
    const input = inputRef.current;
    if (input) {
      input.style.height = "auto";
      input.style.height = `${Math.min(input.scrollHeight, 160)}px`;
    }
  }, [value]);
  const canSubmit =
    Boolean(onSubmit) && Boolean(value.trim()) && !disabled && !busy;

  return (
    <div className="composer-region">
      <form
        className={`composer ${disabled ? "is-disabled" : ""}`}
        aria-label="Message composer"
        aria-busy={busy}
        onSubmit={(event) => {
          event.preventDefault();
          if (canSubmit) onSubmit?.(value.trim());
        }}
      >
        <label className="sr-only" htmlFor={inputId}>
          Message YoriGPT
        </label>
        <textarea
          ref={inputRef}
          id={inputId}
          rows={1}
          value={value}
          onChange={(event) => onValueChange(event.target.value)}
          placeholder="A question, an idea, a little curiosity…"
          aria-describedby={hintId}
          disabled={disabled || busy}
        />
        <div className="composer-toolbar">
          <div className="composer-tools">
            <IconButton
              icon="attach"
              label="Attachments unavailable in this preview"
              disabled
            />
            <span>Make room for a thought.</span>
          </div>
          <button
            type="submit"
            className="send-button"
            disabled={!canSubmit}
            aria-label={
              busy
                ? "Sending message"
                : onSubmit
                  ? "Send message"
                  : "Sending unavailable in this preview"
            }
            title={onSubmit ? "Send message" : "Sending is not connected yet"}
          >
            {busy ? (
              <span className="loading-spinner" />
            ) : (
              <Icon name="arrow" />
            )}
          </button>
        </div>
      </form>
      {error ? (
        <p className="composer-error" role="alert">
          {error}
        </p>
      ) : null}
      <p className="composer-disclaimer" id={hintId}>
        <span className="preview-dot" /> {onSubmit ? "Saved" : "UI preview"}{" "}
        <span aria-hidden="true">·</span>{" "}
        {onSubmit
          ? "Your message is stored and the reply is generated by the configured model."
          : "Messages aren’t sent or saved."}
      </p>
    </div>
  );
}
